recipepicker:
  server_url: ${RECIPEPICKER_DOMAIN:https://kokud.dev/}

spring:
  data:
    mongodb:
      host: ${MONGOHOST}
      port : ${MONGOPORT}
      database : ${MONGODB}
      username: ${MONGOUSER}
      password: ${MONGOPASSWORD}
      authentication-database: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com'
          issuer-uri: ${ISSUER}
          audiences: ${AUDIENCES}